# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2023.1.3\bin\cmake\win\x64\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2023.1.3\bin\cmake\win\x64\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2023.1.3\bin\cmake\win\x64\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2023.1.3\bin\cmake\win\x64\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kursovaya

# Build rule for target.
kursovaya: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 kursovaya
.PHONY : kursovaya

# fast build rule for target.
kursovaya/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/build
.PHONY : kursovaya/fast

Comparators/compare_keys.obj: Comparators/compare_keys.cpp.obj
.PHONY : Comparators/compare_keys.obj

# target to build an object file
Comparators/compare_keys.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Comparators/compare_keys.cpp.obj
.PHONY : Comparators/compare_keys.cpp.obj

Comparators/compare_keys.i: Comparators/compare_keys.cpp.i
.PHONY : Comparators/compare_keys.i

# target to preprocess a source file
Comparators/compare_keys.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Comparators/compare_keys.cpp.i
.PHONY : Comparators/compare_keys.cpp.i

Comparators/compare_keys.s: Comparators/compare_keys.cpp.s
.PHONY : Comparators/compare_keys.s

# target to generate assembly for a file
Comparators/compare_keys.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Comparators/compare_keys.cpp.s
.PHONY : Comparators/compare_keys.cpp.s

Comparators/compare_strings.obj: Comparators/compare_strings.cpp.obj
.PHONY : Comparators/compare_strings.obj

# target to build an object file
Comparators/compare_strings.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Comparators/compare_strings.cpp.obj
.PHONY : Comparators/compare_strings.cpp.obj

Comparators/compare_strings.i: Comparators/compare_strings.cpp.i
.PHONY : Comparators/compare_strings.i

# target to preprocess a source file
Comparators/compare_strings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Comparators/compare_strings.cpp.i
.PHONY : Comparators/compare_strings.cpp.i

Comparators/compare_strings.s: Comparators/compare_strings.cpp.s
.PHONY : Comparators/compare_strings.s

# target to generate assembly for a file
Comparators/compare_strings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Comparators/compare_strings.cpp.s
.PHONY : Comparators/compare_strings.cpp.s

Data_structures/data_collection.obj: Data_structures/data_collection.cpp.obj
.PHONY : Data_structures/data_collection.obj

# target to build an object file
Data_structures/data_collection.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Data_structures/data_collection.cpp.obj
.PHONY : Data_structures/data_collection.cpp.obj

Data_structures/data_collection.i: Data_structures/data_collection.cpp.i
.PHONY : Data_structures/data_collection.i

# target to preprocess a source file
Data_structures/data_collection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Data_structures/data_collection.cpp.i
.PHONY : Data_structures/data_collection.cpp.i

Data_structures/data_collection.s: Data_structures/data_collection.cpp.s
.PHONY : Data_structures/data_collection.s

# target to generate assembly for a file
Data_structures/data_collection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Data_structures/data_collection.cpp.s
.PHONY : Data_structures/data_collection.cpp.s

Data_structures/database.obj: Data_structures/database.cpp.obj
.PHONY : Data_structures/database.obj

# target to build an object file
Data_structures/database.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Data_structures/database.cpp.obj
.PHONY : Data_structures/database.cpp.obj

Data_structures/database.i: Data_structures/database.cpp.i
.PHONY : Data_structures/database.i

# target to preprocess a source file
Data_structures/database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Data_structures/database.cpp.i
.PHONY : Data_structures/database.cpp.i

Data_structures/database.s: Data_structures/database.cpp.s
.PHONY : Data_structures/database.s

# target to generate assembly for a file
Data_structures/database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Data_structures/database.cpp.s
.PHONY : Data_structures/database.cpp.s

Data_structures/pool.obj: Data_structures/pool.cpp.obj
.PHONY : Data_structures/pool.obj

# target to build an object file
Data_structures/pool.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Data_structures/pool.cpp.obj
.PHONY : Data_structures/pool.cpp.obj

Data_structures/pool.i: Data_structures/pool.cpp.i
.PHONY : Data_structures/pool.i

# target to preprocess a source file
Data_structures/pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Data_structures/pool.cpp.i
.PHONY : Data_structures/pool.cpp.i

Data_structures/pool.s: Data_structures/pool.cpp.s
.PHONY : Data_structures/pool.s

# target to generate assembly for a file
Data_structures/pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Data_structures/pool.cpp.s
.PHONY : Data_structures/pool.cpp.s

Data_structures/scheme.obj: Data_structures/scheme.cpp.obj
.PHONY : Data_structures/scheme.obj

# target to build an object file
Data_structures/scheme.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Data_structures/scheme.cpp.obj
.PHONY : Data_structures/scheme.cpp.obj

Data_structures/scheme.i: Data_structures/scheme.cpp.i
.PHONY : Data_structures/scheme.i

# target to preprocess a source file
Data_structures/scheme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Data_structures/scheme.cpp.i
.PHONY : Data_structures/scheme.cpp.i

Data_structures/scheme.s: Data_structures/scheme.cpp.s
.PHONY : Data_structures/scheme.s

# target to generate assembly for a file
Data_structures/scheme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Data_structures/scheme.cpp.s
.PHONY : Data_structures/scheme.cpp.s

Logger/JSON/json_impl.obj: Logger/JSON/json_impl.cpp.obj
.PHONY : Logger/JSON/json_impl.obj

# target to build an object file
Logger/JSON/json_impl.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Logger/JSON/json_impl.cpp.obj
.PHONY : Logger/JSON/json_impl.cpp.obj

Logger/JSON/json_impl.i: Logger/JSON/json_impl.cpp.i
.PHONY : Logger/JSON/json_impl.i

# target to preprocess a source file
Logger/JSON/json_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Logger/JSON/json_impl.cpp.i
.PHONY : Logger/JSON/json_impl.cpp.i

Logger/JSON/json_impl.s: Logger/JSON/json_impl.cpp.s
.PHONY : Logger/JSON/json_impl.s

# target to generate assembly for a file
Logger/JSON/json_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Logger/JSON/json_impl.cpp.s
.PHONY : Logger/JSON/json_impl.cpp.s

Logger/builder_impl.obj: Logger/builder_impl.cpp.obj
.PHONY : Logger/builder_impl.obj

# target to build an object file
Logger/builder_impl.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Logger/builder_impl.cpp.obj
.PHONY : Logger/builder_impl.cpp.obj

Logger/builder_impl.i: Logger/builder_impl.cpp.i
.PHONY : Logger/builder_impl.i

# target to preprocess a source file
Logger/builder_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Logger/builder_impl.cpp.i
.PHONY : Logger/builder_impl.cpp.i

Logger/builder_impl.s: Logger/builder_impl.cpp.s
.PHONY : Logger/builder_impl.s

# target to generate assembly for a file
Logger/builder_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Logger/builder_impl.cpp.s
.PHONY : Logger/builder_impl.cpp.s

Logger/log_hold.obj: Logger/log_hold.cpp.obj
.PHONY : Logger/log_hold.obj

# target to build an object file
Logger/log_hold.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Logger/log_hold.cpp.obj
.PHONY : Logger/log_hold.cpp.obj

Logger/log_hold.i: Logger/log_hold.cpp.i
.PHONY : Logger/log_hold.i

# target to preprocess a source file
Logger/log_hold.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Logger/log_hold.cpp.i
.PHONY : Logger/log_hold.cpp.i

Logger/log_hold.s: Logger/log_hold.cpp.s
.PHONY : Logger/log_hold.s

# target to generate assembly for a file
Logger/log_hold.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Logger/log_hold.cpp.s
.PHONY : Logger/log_hold.cpp.s

Logger/logger_impl.obj: Logger/logger_impl.cpp.obj
.PHONY : Logger/logger_impl.obj

# target to build an object file
Logger/logger_impl.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Logger/logger_impl.cpp.obj
.PHONY : Logger/logger_impl.cpp.obj

Logger/logger_impl.i: Logger/logger_impl.cpp.i
.PHONY : Logger/logger_impl.i

# target to preprocess a source file
Logger/logger_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Logger/logger_impl.cpp.i
.PHONY : Logger/logger_impl.cpp.i

Logger/logger_impl.s: Logger/logger_impl.cpp.s
.PHONY : Logger/logger_impl.s

# target to generate assembly for a file
Logger/logger_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Logger/logger_impl.cpp.s
.PHONY : Logger/logger_impl.cpp.s

Memory_Alloc/border_descriptors_alloc.obj: Memory_Alloc/border_descriptors_alloc.cpp.obj
.PHONY : Memory_Alloc/border_descriptors_alloc.obj

# target to build an object file
Memory_Alloc/border_descriptors_alloc.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/border_descriptors_alloc.cpp.obj
.PHONY : Memory_Alloc/border_descriptors_alloc.cpp.obj

Memory_Alloc/border_descriptors_alloc.i: Memory_Alloc/border_descriptors_alloc.cpp.i
.PHONY : Memory_Alloc/border_descriptors_alloc.i

# target to preprocess a source file
Memory_Alloc/border_descriptors_alloc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/border_descriptors_alloc.cpp.i
.PHONY : Memory_Alloc/border_descriptors_alloc.cpp.i

Memory_Alloc/border_descriptors_alloc.s: Memory_Alloc/border_descriptors_alloc.cpp.s
.PHONY : Memory_Alloc/border_descriptors_alloc.s

# target to generate assembly for a file
Memory_Alloc/border_descriptors_alloc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/border_descriptors_alloc.cpp.s
.PHONY : Memory_Alloc/border_descriptors_alloc.cpp.s

Memory_Alloc/buddy_alloc.obj: Memory_Alloc/buddy_alloc.cpp.obj
.PHONY : Memory_Alloc/buddy_alloc.obj

# target to build an object file
Memory_Alloc/buddy_alloc.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/buddy_alloc.cpp.obj
.PHONY : Memory_Alloc/buddy_alloc.cpp.obj

Memory_Alloc/buddy_alloc.i: Memory_Alloc/buddy_alloc.cpp.i
.PHONY : Memory_Alloc/buddy_alloc.i

# target to preprocess a source file
Memory_Alloc/buddy_alloc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/buddy_alloc.cpp.i
.PHONY : Memory_Alloc/buddy_alloc.cpp.i

Memory_Alloc/buddy_alloc.s: Memory_Alloc/buddy_alloc.cpp.s
.PHONY : Memory_Alloc/buddy_alloc.s

# target to generate assembly for a file
Memory_Alloc/buddy_alloc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/buddy_alloc.cpp.s
.PHONY : Memory_Alloc/buddy_alloc.cpp.s

Memory_Alloc/global_heap_alloc.obj: Memory_Alloc/global_heap_alloc.cpp.obj
.PHONY : Memory_Alloc/global_heap_alloc.obj

# target to build an object file
Memory_Alloc/global_heap_alloc.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/global_heap_alloc.cpp.obj
.PHONY : Memory_Alloc/global_heap_alloc.cpp.obj

Memory_Alloc/global_heap_alloc.i: Memory_Alloc/global_heap_alloc.cpp.i
.PHONY : Memory_Alloc/global_heap_alloc.i

# target to preprocess a source file
Memory_Alloc/global_heap_alloc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/global_heap_alloc.cpp.i
.PHONY : Memory_Alloc/global_heap_alloc.cpp.i

Memory_Alloc/global_heap_alloc.s: Memory_Alloc/global_heap_alloc.cpp.s
.PHONY : Memory_Alloc/global_heap_alloc.s

# target to generate assembly for a file
Memory_Alloc/global_heap_alloc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/global_heap_alloc.cpp.s
.PHONY : Memory_Alloc/global_heap_alloc.cpp.s

Memory_Alloc/hold_memory.obj: Memory_Alloc/hold_memory.cpp.obj
.PHONY : Memory_Alloc/hold_memory.obj

# target to build an object file
Memory_Alloc/hold_memory.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/hold_memory.cpp.obj
.PHONY : Memory_Alloc/hold_memory.cpp.obj

Memory_Alloc/hold_memory.i: Memory_Alloc/hold_memory.cpp.i
.PHONY : Memory_Alloc/hold_memory.i

# target to preprocess a source file
Memory_Alloc/hold_memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/hold_memory.cpp.i
.PHONY : Memory_Alloc/hold_memory.cpp.i

Memory_Alloc/hold_memory.s: Memory_Alloc/hold_memory.cpp.s
.PHONY : Memory_Alloc/hold_memory.s

# target to generate assembly for a file
Memory_Alloc/hold_memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/hold_memory.cpp.s
.PHONY : Memory_Alloc/hold_memory.cpp.s

Memory_Alloc/memory.obj: Memory_Alloc/memory.cpp.obj
.PHONY : Memory_Alloc/memory.obj

# target to build an object file
Memory_Alloc/memory.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/memory.cpp.obj
.PHONY : Memory_Alloc/memory.cpp.obj

Memory_Alloc/memory.i: Memory_Alloc/memory.cpp.i
.PHONY : Memory_Alloc/memory.i

# target to preprocess a source file
Memory_Alloc/memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/memory.cpp.i
.PHONY : Memory_Alloc/memory.cpp.i

Memory_Alloc/memory.s: Memory_Alloc/memory.cpp.s
.PHONY : Memory_Alloc/memory.s

# target to generate assembly for a file
Memory_Alloc/memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/memory.cpp.s
.PHONY : Memory_Alloc/memory.cpp.s

Memory_Alloc/sorted_list_alloc.obj: Memory_Alloc/sorted_list_alloc.cpp.obj
.PHONY : Memory_Alloc/sorted_list_alloc.obj

# target to build an object file
Memory_Alloc/sorted_list_alloc.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/sorted_list_alloc.cpp.obj
.PHONY : Memory_Alloc/sorted_list_alloc.cpp.obj

Memory_Alloc/sorted_list_alloc.i: Memory_Alloc/sorted_list_alloc.cpp.i
.PHONY : Memory_Alloc/sorted_list_alloc.i

# target to preprocess a source file
Memory_Alloc/sorted_list_alloc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/sorted_list_alloc.cpp.i
.PHONY : Memory_Alloc/sorted_list_alloc.cpp.i

Memory_Alloc/sorted_list_alloc.s: Memory_Alloc/sorted_list_alloc.cpp.s
.PHONY : Memory_Alloc/sorted_list_alloc.s

# target to generate assembly for a file
Memory_Alloc/sorted_list_alloc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Memory_Alloc/sorted_list_alloc.cpp.s
.PHONY : Memory_Alloc/sorted_list_alloc.cpp.s

Request_Handler/command.obj: Request_Handler/command.cpp.obj
.PHONY : Request_Handler/command.obj

# target to build an object file
Request_Handler/command.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command.cpp.obj
.PHONY : Request_Handler/command.cpp.obj

Request_Handler/command.i: Request_Handler/command.cpp.i
.PHONY : Request_Handler/command.i

# target to preprocess a source file
Request_Handler/command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command.cpp.i
.PHONY : Request_Handler/command.cpp.i

Request_Handler/command.s: Request_Handler/command.cpp.s
.PHONY : Request_Handler/command.s

# target to generate assembly for a file
Request_Handler/command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command.cpp.s
.PHONY : Request_Handler/command.cpp.s

Request_Handler/command_add_collection.obj: Request_Handler/command_add_collection.cpp.obj
.PHONY : Request_Handler/command_add_collection.obj

# target to build an object file
Request_Handler/command_add_collection.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_add_collection.cpp.obj
.PHONY : Request_Handler/command_add_collection.cpp.obj

Request_Handler/command_add_collection.i: Request_Handler/command_add_collection.cpp.i
.PHONY : Request_Handler/command_add_collection.i

# target to preprocess a source file
Request_Handler/command_add_collection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_add_collection.cpp.i
.PHONY : Request_Handler/command_add_collection.cpp.i

Request_Handler/command_add_collection.s: Request_Handler/command_add_collection.cpp.s
.PHONY : Request_Handler/command_add_collection.s

# target to generate assembly for a file
Request_Handler/command_add_collection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_add_collection.cpp.s
.PHONY : Request_Handler/command_add_collection.cpp.s

Request_Handler/command_add_data.obj: Request_Handler/command_add_data.cpp.obj
.PHONY : Request_Handler/command_add_data.obj

# target to build an object file
Request_Handler/command_add_data.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_add_data.cpp.obj
.PHONY : Request_Handler/command_add_data.cpp.obj

Request_Handler/command_add_data.i: Request_Handler/command_add_data.cpp.i
.PHONY : Request_Handler/command_add_data.i

# target to preprocess a source file
Request_Handler/command_add_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_add_data.cpp.i
.PHONY : Request_Handler/command_add_data.cpp.i

Request_Handler/command_add_data.s: Request_Handler/command_add_data.cpp.s
.PHONY : Request_Handler/command_add_data.s

# target to generate assembly for a file
Request_Handler/command_add_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_add_data.cpp.s
.PHONY : Request_Handler/command_add_data.cpp.s

Request_Handler/command_add_pool.obj: Request_Handler/command_add_pool.cpp.obj
.PHONY : Request_Handler/command_add_pool.obj

# target to build an object file
Request_Handler/command_add_pool.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_add_pool.cpp.obj
.PHONY : Request_Handler/command_add_pool.cpp.obj

Request_Handler/command_add_pool.i: Request_Handler/command_add_pool.cpp.i
.PHONY : Request_Handler/command_add_pool.i

# target to preprocess a source file
Request_Handler/command_add_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_add_pool.cpp.i
.PHONY : Request_Handler/command_add_pool.cpp.i

Request_Handler/command_add_pool.s: Request_Handler/command_add_pool.cpp.s
.PHONY : Request_Handler/command_add_pool.s

# target to generate assembly for a file
Request_Handler/command_add_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_add_pool.cpp.s
.PHONY : Request_Handler/command_add_pool.cpp.s

Request_Handler/command_add_scheme.obj: Request_Handler/command_add_scheme.cpp.obj
.PHONY : Request_Handler/command_add_scheme.obj

# target to build an object file
Request_Handler/command_add_scheme.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_add_scheme.cpp.obj
.PHONY : Request_Handler/command_add_scheme.cpp.obj

Request_Handler/command_add_scheme.i: Request_Handler/command_add_scheme.cpp.i
.PHONY : Request_Handler/command_add_scheme.i

# target to preprocess a source file
Request_Handler/command_add_scheme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_add_scheme.cpp.i
.PHONY : Request_Handler/command_add_scheme.cpp.i

Request_Handler/command_add_scheme.s: Request_Handler/command_add_scheme.cpp.s
.PHONY : Request_Handler/command_add_scheme.s

# target to generate assembly for a file
Request_Handler/command_add_scheme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_add_scheme.cpp.s
.PHONY : Request_Handler/command_add_scheme.cpp.s

Request_Handler/command_get_data.obj: Request_Handler/command_get_data.cpp.obj
.PHONY : Request_Handler/command_get_data.obj

# target to build an object file
Request_Handler/command_get_data.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_get_data.cpp.obj
.PHONY : Request_Handler/command_get_data.cpp.obj

Request_Handler/command_get_data.i: Request_Handler/command_get_data.cpp.i
.PHONY : Request_Handler/command_get_data.i

# target to preprocess a source file
Request_Handler/command_get_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_get_data.cpp.i
.PHONY : Request_Handler/command_get_data.cpp.i

Request_Handler/command_get_data.s: Request_Handler/command_get_data.cpp.s
.PHONY : Request_Handler/command_get_data.s

# target to generate assembly for a file
Request_Handler/command_get_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_get_data.cpp.s
.PHONY : Request_Handler/command_get_data.cpp.s

Request_Handler/command_get_data_between.obj: Request_Handler/command_get_data_between.cpp.obj
.PHONY : Request_Handler/command_get_data_between.obj

# target to build an object file
Request_Handler/command_get_data_between.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_get_data_between.cpp.obj
.PHONY : Request_Handler/command_get_data_between.cpp.obj

Request_Handler/command_get_data_between.i: Request_Handler/command_get_data_between.cpp.i
.PHONY : Request_Handler/command_get_data_between.i

# target to preprocess a source file
Request_Handler/command_get_data_between.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_get_data_between.cpp.i
.PHONY : Request_Handler/command_get_data_between.cpp.i

Request_Handler/command_get_data_between.s: Request_Handler/command_get_data_between.cpp.s
.PHONY : Request_Handler/command_get_data_between.s

# target to generate assembly for a file
Request_Handler/command_get_data_between.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_get_data_between.cpp.s
.PHONY : Request_Handler/command_get_data_between.cpp.s

Request_Handler/command_remove_collection.obj: Request_Handler/command_remove_collection.cpp.obj
.PHONY : Request_Handler/command_remove_collection.obj

# target to build an object file
Request_Handler/command_remove_collection.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_remove_collection.cpp.obj
.PHONY : Request_Handler/command_remove_collection.cpp.obj

Request_Handler/command_remove_collection.i: Request_Handler/command_remove_collection.cpp.i
.PHONY : Request_Handler/command_remove_collection.i

# target to preprocess a source file
Request_Handler/command_remove_collection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_remove_collection.cpp.i
.PHONY : Request_Handler/command_remove_collection.cpp.i

Request_Handler/command_remove_collection.s: Request_Handler/command_remove_collection.cpp.s
.PHONY : Request_Handler/command_remove_collection.s

# target to generate assembly for a file
Request_Handler/command_remove_collection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_remove_collection.cpp.s
.PHONY : Request_Handler/command_remove_collection.cpp.s

Request_Handler/command_remove_data.obj: Request_Handler/command_remove_data.cpp.obj
.PHONY : Request_Handler/command_remove_data.obj

# target to build an object file
Request_Handler/command_remove_data.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_remove_data.cpp.obj
.PHONY : Request_Handler/command_remove_data.cpp.obj

Request_Handler/command_remove_data.i: Request_Handler/command_remove_data.cpp.i
.PHONY : Request_Handler/command_remove_data.i

# target to preprocess a source file
Request_Handler/command_remove_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_remove_data.cpp.i
.PHONY : Request_Handler/command_remove_data.cpp.i

Request_Handler/command_remove_data.s: Request_Handler/command_remove_data.cpp.s
.PHONY : Request_Handler/command_remove_data.s

# target to generate assembly for a file
Request_Handler/command_remove_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_remove_data.cpp.s
.PHONY : Request_Handler/command_remove_data.cpp.s

Request_Handler/command_remove_pool.obj: Request_Handler/command_remove_pool.cpp.obj
.PHONY : Request_Handler/command_remove_pool.obj

# target to build an object file
Request_Handler/command_remove_pool.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_remove_pool.cpp.obj
.PHONY : Request_Handler/command_remove_pool.cpp.obj

Request_Handler/command_remove_pool.i: Request_Handler/command_remove_pool.cpp.i
.PHONY : Request_Handler/command_remove_pool.i

# target to preprocess a source file
Request_Handler/command_remove_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_remove_pool.cpp.i
.PHONY : Request_Handler/command_remove_pool.cpp.i

Request_Handler/command_remove_pool.s: Request_Handler/command_remove_pool.cpp.s
.PHONY : Request_Handler/command_remove_pool.s

# target to generate assembly for a file
Request_Handler/command_remove_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_remove_pool.cpp.s
.PHONY : Request_Handler/command_remove_pool.cpp.s

Request_Handler/command_remove_scheme.obj: Request_Handler/command_remove_scheme.cpp.obj
.PHONY : Request_Handler/command_remove_scheme.obj

# target to build an object file
Request_Handler/command_remove_scheme.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_remove_scheme.cpp.obj
.PHONY : Request_Handler/command_remove_scheme.cpp.obj

Request_Handler/command_remove_scheme.i: Request_Handler/command_remove_scheme.cpp.i
.PHONY : Request_Handler/command_remove_scheme.i

# target to preprocess a source file
Request_Handler/command_remove_scheme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_remove_scheme.cpp.i
.PHONY : Request_Handler/command_remove_scheme.cpp.i

Request_Handler/command_remove_scheme.s: Request_Handler/command_remove_scheme.cpp.s
.PHONY : Request_Handler/command_remove_scheme.s

# target to generate assembly for a file
Request_Handler/command_remove_scheme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_remove_scheme.cpp.s
.PHONY : Request_Handler/command_remove_scheme.cpp.s

Request_Handler/command_update_data.obj: Request_Handler/command_update_data.cpp.obj
.PHONY : Request_Handler/command_update_data.obj

# target to build an object file
Request_Handler/command_update_data.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_update_data.cpp.obj
.PHONY : Request_Handler/command_update_data.cpp.obj

Request_Handler/command_update_data.i: Request_Handler/command_update_data.cpp.i
.PHONY : Request_Handler/command_update_data.i

# target to preprocess a source file
Request_Handler/command_update_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_update_data.cpp.i
.PHONY : Request_Handler/command_update_data.cpp.i

Request_Handler/command_update_data.s: Request_Handler/command_update_data.cpp.s
.PHONY : Request_Handler/command_update_data.s

# target to generate assembly for a file
Request_Handler/command_update_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/command_update_data.cpp.s
.PHONY : Request_Handler/command_update_data.cpp.s

Request_Handler/request_handler_with_command.obj: Request_Handler/request_handler_with_command.cpp.obj
.PHONY : Request_Handler/request_handler_with_command.obj

# target to build an object file
Request_Handler/request_handler_with_command.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/request_handler_with_command.cpp.obj
.PHONY : Request_Handler/request_handler_with_command.cpp.obj

Request_Handler/request_handler_with_command.i: Request_Handler/request_handler_with_command.cpp.i
.PHONY : Request_Handler/request_handler_with_command.i

# target to preprocess a source file
Request_Handler/request_handler_with_command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/request_handler_with_command.cpp.i
.PHONY : Request_Handler/request_handler_with_command.cpp.i

Request_Handler/request_handler_with_command.s: Request_Handler/request_handler_with_command.cpp.s
.PHONY : Request_Handler/request_handler_with_command.s

# target to generate assembly for a file
Request_Handler/request_handler_with_command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/request_handler_with_command.cpp.s
.PHONY : Request_Handler/request_handler_with_command.cpp.s

Request_Handler/request_handler_with_command_chain.obj: Request_Handler/request_handler_with_command_chain.cpp.obj
.PHONY : Request_Handler/request_handler_with_command_chain.obj

# target to build an object file
Request_Handler/request_handler_with_command_chain.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/request_handler_with_command_chain.cpp.obj
.PHONY : Request_Handler/request_handler_with_command_chain.cpp.obj

Request_Handler/request_handler_with_command_chain.i: Request_Handler/request_handler_with_command_chain.cpp.i
.PHONY : Request_Handler/request_handler_with_command_chain.i

# target to preprocess a source file
Request_Handler/request_handler_with_command_chain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/request_handler_with_command_chain.cpp.i
.PHONY : Request_Handler/request_handler_with_command_chain.cpp.i

Request_Handler/request_handler_with_command_chain.s: Request_Handler/request_handler_with_command_chain.cpp.s
.PHONY : Request_Handler/request_handler_with_command_chain.s

# target to generate assembly for a file
Request_Handler/request_handler_with_command_chain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/Request_Handler/request_handler_with_command_chain.cpp.s
.PHONY : Request_Handler/request_handler_with_command_chain.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\kursovaya.dir\build.make CMakeFiles/kursovaya.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... kursovaya
	@echo ... Comparators/compare_keys.obj
	@echo ... Comparators/compare_keys.i
	@echo ... Comparators/compare_keys.s
	@echo ... Comparators/compare_strings.obj
	@echo ... Comparators/compare_strings.i
	@echo ... Comparators/compare_strings.s
	@echo ... Data_structures/data_collection.obj
	@echo ... Data_structures/data_collection.i
	@echo ... Data_structures/data_collection.s
	@echo ... Data_structures/database.obj
	@echo ... Data_structures/database.i
	@echo ... Data_structures/database.s
	@echo ... Data_structures/pool.obj
	@echo ... Data_structures/pool.i
	@echo ... Data_structures/pool.s
	@echo ... Data_structures/scheme.obj
	@echo ... Data_structures/scheme.i
	@echo ... Data_structures/scheme.s
	@echo ... Logger/JSON/json_impl.obj
	@echo ... Logger/JSON/json_impl.i
	@echo ... Logger/JSON/json_impl.s
	@echo ... Logger/builder_impl.obj
	@echo ... Logger/builder_impl.i
	@echo ... Logger/builder_impl.s
	@echo ... Logger/log_hold.obj
	@echo ... Logger/log_hold.i
	@echo ... Logger/log_hold.s
	@echo ... Logger/logger_impl.obj
	@echo ... Logger/logger_impl.i
	@echo ... Logger/logger_impl.s
	@echo ... Memory_Alloc/border_descriptors_alloc.obj
	@echo ... Memory_Alloc/border_descriptors_alloc.i
	@echo ... Memory_Alloc/border_descriptors_alloc.s
	@echo ... Memory_Alloc/buddy_alloc.obj
	@echo ... Memory_Alloc/buddy_alloc.i
	@echo ... Memory_Alloc/buddy_alloc.s
	@echo ... Memory_Alloc/global_heap_alloc.obj
	@echo ... Memory_Alloc/global_heap_alloc.i
	@echo ... Memory_Alloc/global_heap_alloc.s
	@echo ... Memory_Alloc/hold_memory.obj
	@echo ... Memory_Alloc/hold_memory.i
	@echo ... Memory_Alloc/hold_memory.s
	@echo ... Memory_Alloc/memory.obj
	@echo ... Memory_Alloc/memory.i
	@echo ... Memory_Alloc/memory.s
	@echo ... Memory_Alloc/sorted_list_alloc.obj
	@echo ... Memory_Alloc/sorted_list_alloc.i
	@echo ... Memory_Alloc/sorted_list_alloc.s
	@echo ... Request_Handler/command.obj
	@echo ... Request_Handler/command.i
	@echo ... Request_Handler/command.s
	@echo ... Request_Handler/command_add_collection.obj
	@echo ... Request_Handler/command_add_collection.i
	@echo ... Request_Handler/command_add_collection.s
	@echo ... Request_Handler/command_add_data.obj
	@echo ... Request_Handler/command_add_data.i
	@echo ... Request_Handler/command_add_data.s
	@echo ... Request_Handler/command_add_pool.obj
	@echo ... Request_Handler/command_add_pool.i
	@echo ... Request_Handler/command_add_pool.s
	@echo ... Request_Handler/command_add_scheme.obj
	@echo ... Request_Handler/command_add_scheme.i
	@echo ... Request_Handler/command_add_scheme.s
	@echo ... Request_Handler/command_get_data.obj
	@echo ... Request_Handler/command_get_data.i
	@echo ... Request_Handler/command_get_data.s
	@echo ... Request_Handler/command_get_data_between.obj
	@echo ... Request_Handler/command_get_data_between.i
	@echo ... Request_Handler/command_get_data_between.s
	@echo ... Request_Handler/command_remove_collection.obj
	@echo ... Request_Handler/command_remove_collection.i
	@echo ... Request_Handler/command_remove_collection.s
	@echo ... Request_Handler/command_remove_data.obj
	@echo ... Request_Handler/command_remove_data.i
	@echo ... Request_Handler/command_remove_data.s
	@echo ... Request_Handler/command_remove_pool.obj
	@echo ... Request_Handler/command_remove_pool.i
	@echo ... Request_Handler/command_remove_pool.s
	@echo ... Request_Handler/command_remove_scheme.obj
	@echo ... Request_Handler/command_remove_scheme.i
	@echo ... Request_Handler/command_remove_scheme.s
	@echo ... Request_Handler/command_update_data.obj
	@echo ... Request_Handler/command_update_data.i
	@echo ... Request_Handler/command_update_data.s
	@echo ... Request_Handler/request_handler_with_command.obj
	@echo ... Request_Handler/request_handler_with_command.i
	@echo ... Request_Handler/request_handler_with_command.s
	@echo ... Request_Handler/request_handler_with_command_chain.obj
	@echo ... Request_Handler/request_handler_with_command_chain.i
	@echo ... Request_Handler/request_handler_with_command_chain.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

