# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.25

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2023.1.3\bin\cmake\win\x64\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2023.1.3\bin\cmake\win\x64\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug

# Include any dependencies generated for this target.
include CMakeFiles/Zaitsevs_cursed_project.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/Zaitsevs_cursed_project.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/Zaitsevs_cursed_project.dir/flags.make

CMakeFiles/Zaitsevs_cursed_project.dir/main.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/main.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/main.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/main.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/main.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/main.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\main.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\main.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\main.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/main.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\main.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\main.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/main.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\main.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\main.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Logger/builder_impl.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Logger/builder_impl.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Logger/builder_impl.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Logger/builder_impl.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Logger/builder_impl.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Logger/builder_impl.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Logger\builder_impl.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Logger\builder_impl.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Logger\builder_impl.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Logger/builder_impl.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Logger/builder_impl.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Logger\builder_impl.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Logger\builder_impl.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Logger/builder_impl.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Logger/builder_impl.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Logger\builder_impl.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Logger\builder_impl.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Logger/logger_impl.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Logger/logger_impl.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Logger/logger_impl.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Logger/logger_impl.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Logger/logger_impl.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Logger/logger_impl.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Logger\logger_impl.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Logger\logger_impl.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Logger\logger_impl.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Logger/logger_impl.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Logger/logger_impl.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Logger\logger_impl.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Logger\logger_impl.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Logger/logger_impl.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Logger/logger_impl.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Logger\logger_impl.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Logger\logger_impl.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Logger/JSON/json_impl.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Logger/JSON/json_impl.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Logger/JSON/json_impl.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Logger/JSON/json_impl.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Logger/JSON/json_impl.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Logger/JSON/json_impl.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Logger\JSON\json_impl.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Logger\JSON\json_impl.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Logger\JSON\json_impl.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Logger/JSON/json_impl.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Logger/JSON/json_impl.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Logger\JSON\json_impl.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Logger\JSON\json_impl.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Logger/JSON/json_impl.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Logger/JSON/json_impl.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Logger\JSON\json_impl.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Logger\JSON\json_impl.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Logger/log_hold.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Logger/log_hold.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Logger/log_hold.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Logger/log_hold.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Logger/log_hold.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Logger/log_hold.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Logger\log_hold.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Logger\log_hold.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Logger\log_hold.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Logger/log_hold.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Logger/log_hold.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Logger\log_hold.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Logger\log_hold.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Logger/log_hold.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Logger/log_hold.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Logger\log_hold.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Logger\log_hold.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/memory.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/memory.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Memory_Alloc/memory.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/memory.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/memory.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/memory.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\memory.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\memory.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\memory.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/memory.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/memory.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\memory.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\memory.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/memory.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/memory.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\memory.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\memory.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/global_heap_alloc.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/global_heap_alloc.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Memory_Alloc/global_heap_alloc.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/global_heap_alloc.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/global_heap_alloc.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/global_heap_alloc.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\global_heap_alloc.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\global_heap_alloc.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\global_heap_alloc.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/global_heap_alloc.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/global_heap_alloc.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\global_heap_alloc.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\global_heap_alloc.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/global_heap_alloc.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/global_heap_alloc.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\global_heap_alloc.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\global_heap_alloc.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/sorted_list_alloc.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/sorted_list_alloc.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Memory_Alloc/sorted_list_alloc.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/sorted_list_alloc.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/sorted_list_alloc.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/sorted_list_alloc.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\sorted_list_alloc.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\sorted_list_alloc.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\sorted_list_alloc.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/sorted_list_alloc.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/sorted_list_alloc.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\sorted_list_alloc.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\sorted_list_alloc.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/sorted_list_alloc.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/sorted_list_alloc.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\sorted_list_alloc.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\sorted_list_alloc.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/border_descriptors_alloc.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/border_descriptors_alloc.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Memory_Alloc/border_descriptors_alloc.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/border_descriptors_alloc.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_9) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/border_descriptors_alloc.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/border_descriptors_alloc.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\border_descriptors_alloc.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\border_descriptors_alloc.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\border_descriptors_alloc.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/border_descriptors_alloc.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/border_descriptors_alloc.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\border_descriptors_alloc.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\border_descriptors_alloc.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/border_descriptors_alloc.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/border_descriptors_alloc.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\border_descriptors_alloc.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\border_descriptors_alloc.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/buddy_alloc.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/buddy_alloc.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Memory_Alloc/buddy_alloc.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/buddy_alloc.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_10) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/buddy_alloc.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/buddy_alloc.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\buddy_alloc.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\buddy_alloc.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\buddy_alloc.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/buddy_alloc.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/buddy_alloc.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\buddy_alloc.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\buddy_alloc.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/buddy_alloc.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/buddy_alloc.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\buddy_alloc.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\buddy_alloc.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/hold_memory.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/hold_memory.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Memory_Alloc/hold_memory.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/hold_memory.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_11) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/hold_memory.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/hold_memory.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\hold_memory.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\hold_memory.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\hold_memory.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/hold_memory.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/hold_memory.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\hold_memory.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\hold_memory.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/hold_memory.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/hold_memory.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Memory_Alloc\hold_memory.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Memory_Alloc\hold_memory.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_strings.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_strings.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Comparators/compare_strings.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_strings.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_12) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_strings.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_strings.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Comparators\compare_strings.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Comparators\compare_strings.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Comparators\compare_strings.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_strings.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_strings.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Comparators\compare_strings.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Comparators\compare_strings.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_strings.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_strings.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Comparators\compare_strings.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Comparators\compare_strings.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_keys.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_keys.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Comparators/compare_keys.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_keys.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_13) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_keys.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_keys.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Comparators\compare_keys.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Comparators\compare_keys.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Comparators\compare_keys.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_keys.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_keys.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Comparators\compare_keys.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Comparators\compare_keys.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_keys.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_keys.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Comparators\compare_keys.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Comparators\compare_keys.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/data_collection.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/data_collection.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Data_structures/data_collection.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/data_collection.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_14) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/data_collection.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/data_collection.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\data_collection.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\data_collection.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Data_structures\data_collection.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/data_collection.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/data_collection.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Data_structures\data_collection.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\data_collection.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/data_collection.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/data_collection.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Data_structures\data_collection.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\data_collection.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/scheme.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/scheme.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Data_structures/scheme.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/scheme.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_15) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/scheme.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/scheme.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\scheme.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\scheme.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Data_structures\scheme.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/scheme.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/scheme.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Data_structures\scheme.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\scheme.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/scheme.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/scheme.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Data_structures\scheme.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\scheme.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/pool.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/pool.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Data_structures/pool.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/pool.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_16) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/pool.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/pool.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\pool.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\pool.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Data_structures\pool.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/pool.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/pool.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Data_structures\pool.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\pool.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/pool.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/pool.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Data_structures\pool.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\pool.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/database.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/database.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Data_structures/database.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/database.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_17) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/database.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/database.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\database.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\database.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Data_structures\database.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/database.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/database.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Data_structures\database.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\database.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/database.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/database.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Data_structures\database.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Data_structures\database.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_collection.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_collection.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_add_collection.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_collection.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_18) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_collection.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_collection.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_collection.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_collection.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_add_collection.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_collection.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_collection.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_add_collection.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_collection.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_collection.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_collection.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_add_collection.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_collection.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_data.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_data.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_add_data.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_data.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_19) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_data.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_data.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_data.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_data.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_add_data.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_data.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_data.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_add_data.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_data.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_data.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_data.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_add_data.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_data.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_pool.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_pool.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_add_pool.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_pool.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_20) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_pool.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_pool.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_pool.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_pool.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_add_pool.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_pool.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_pool.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_add_pool.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_pool.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_pool.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_pool.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_add_pool.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_pool.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_scheme.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_scheme.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_add_scheme.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_scheme.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_21) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_scheme.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_scheme.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_scheme.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_scheme.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_add_scheme.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_scheme.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_scheme.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_add_scheme.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_scheme.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_scheme.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_scheme.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_add_scheme.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_add_scheme.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_get_data.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_22) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_get_data.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_get_data.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_get_data.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_get_data.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_get_data.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_get_data.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_get_data.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data_between.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data_between.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_get_data_between.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data_between.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_23) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data_between.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data_between.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_get_data_between.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_get_data_between.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_get_data_between.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data_between.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data_between.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_get_data_between.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_get_data_between.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data_between.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data_between.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_get_data_between.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_get_data_between.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_collection.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_collection.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_remove_collection.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_collection.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_24) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_collection.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_collection.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_collection.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_collection.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_remove_collection.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_collection.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_collection.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_remove_collection.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_collection.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_collection.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_collection.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_remove_collection.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_collection.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_data.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_data.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_remove_data.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_data.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_25) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_data.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_data.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_data.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_data.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_remove_data.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_data.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_data.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_remove_data.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_data.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_data.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_data.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_remove_data.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_data.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_pool.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_pool.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_remove_pool.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_pool.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_26) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_pool.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_pool.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_pool.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_pool.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_remove_pool.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_pool.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_pool.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_remove_pool.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_pool.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_pool.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_pool.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_remove_pool.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_pool.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_scheme.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_scheme.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_remove_scheme.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_scheme.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_27) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_scheme.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_scheme.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_scheme.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_scheme.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_remove_scheme.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_scheme.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_scheme.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_remove_scheme.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_scheme.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_scheme.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_scheme.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_remove_scheme.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_remove_scheme.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_update_data.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_update_data.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_update_data.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_update_data.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_28) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_update_data.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_update_data.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_update_data.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_update_data.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_update_data.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_update_data.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_update_data.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_update_data.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_update_data.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_update_data.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_update_data.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command_update_data.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command_update_data.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/request_handler_with_command.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_29) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\request_handler_with_command.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\request_handler_with_command.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\request_handler_with_command.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\request_handler_with_command.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\request_handler_with_command.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\request_handler_with_command.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\request_handler_with_command.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command_chain.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command_chain.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/request_handler_with_command_chain.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command_chain.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_30) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command_chain.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command_chain.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\request_handler_with_command_chain.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\request_handler_with_command_chain.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\request_handler_with_command_chain.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command_chain.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command_chain.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\request_handler_with_command_chain.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\request_handler_with_command_chain.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command_chain.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command_chain.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\request_handler_with_command_chain.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\request_handler_with_command_chain.cpp.s

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/flags.make
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command.cpp.obj: E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command.cpp
CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command.cpp.obj: CMakeFiles/Zaitsevs_cursed_project.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_31) "Building CXX object CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command.cpp.obj -MF CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command.cpp.obj.d -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command.cpp.obj -c E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command.cpp

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command.cpp > CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command.cpp.i

CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\Request_Handler\command.cpp -o CMakeFiles\Zaitsevs_cursed_project.dir\Request_Handler\command.cpp.s

# Object files for target Zaitsevs_cursed_project
Zaitsevs_cursed_project_OBJECTS = \
"CMakeFiles/Zaitsevs_cursed_project.dir/main.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Logger/builder_impl.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Logger/logger_impl.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Logger/JSON/json_impl.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Logger/log_hold.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/memory.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/global_heap_alloc.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/sorted_list_alloc.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/border_descriptors_alloc.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/buddy_alloc.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/hold_memory.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_strings.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_keys.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/data_collection.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/scheme.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/pool.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/database.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_collection.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_data.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_pool.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_scheme.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data_between.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_collection.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_data.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_pool.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_scheme.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_update_data.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command_chain.cpp.obj" \
"CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command.cpp.obj"

# External object files for target Zaitsevs_cursed_project
Zaitsevs_cursed_project_EXTERNAL_OBJECTS =

Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/main.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Logger/builder_impl.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Logger/logger_impl.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Logger/JSON/json_impl.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Logger/log_hold.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/memory.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/global_heap_alloc.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/sorted_list_alloc.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/border_descriptors_alloc.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/buddy_alloc.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/hold_memory.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_strings.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_keys.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/data_collection.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/scheme.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/pool.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/database.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_collection.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_data.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_pool.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_scheme.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data_between.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_collection.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_data.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_pool.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_scheme.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_update_data.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command_chain.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command.cpp.obj
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/build.make
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/linkLibs.rsp
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/objects1
Zaitsevs_cursed_project.exe: CMakeFiles/Zaitsevs_cursed_project.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_32) "Linking CXX executable Zaitsevs_cursed_project.exe"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles\Zaitsevs_cursed_project.dir\link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/Zaitsevs_cursed_project.dir/build: Zaitsevs_cursed_project.exe
.PHONY : CMakeFiles/Zaitsevs_cursed_project.dir/build

CMakeFiles/Zaitsevs_cursed_project.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles\Zaitsevs_cursed_project.dir\cmake_clean.cmake
.PHONY : CMakeFiles/Zaitsevs_cursed_project.dir/clean

CMakeFiles/Zaitsevs_cursed_project.dir/depend:
	$(CMAKE_COMMAND) -E cmake_depends "MinGW Makefiles" E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug E:\Downloads\OLDKURSACHI\fundamental-algorithms-main\fundamental-algorithms-main\4Term\Zaitsevs_cursed_project\cmake-build-debug\CMakeFiles\Zaitsevs_cursed_project.dir\DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/Zaitsevs_cursed_project.dir/depend

