
# Consider dependencies only in project.
set(CMAKE_DEPENDS_IN_PROJECT_ONLY OFF)

# The set of languages for which implicit dependencies are needed:
set(CMAKE_DEPENDS_LANGUAGES
  )

# The set of dependency files which are needed:
set(CMAKE_DEPENDS_DEPENDENCY_FILES
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Comparators/compare_keys.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_keys.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_keys.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Comparators/compare_strings.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_strings.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Comparators/compare_strings.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Data_structures/data_collection.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/data_collection.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/data_collection.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Data_structures/database.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/database.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/database.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Data_structures/pool.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/pool.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/pool.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Data_structures/scheme.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/scheme.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Data_structures/scheme.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Logger/JSON/json_impl.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Logger/JSON/json_impl.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Logger/JSON/json_impl.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Logger/builder_impl.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Logger/builder_impl.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Logger/builder_impl.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Logger/log_hold.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Logger/log_hold.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Logger/log_hold.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Logger/logger_impl.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Logger/logger_impl.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Logger/logger_impl.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Memory_Alloc/border_descriptors_alloc.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/border_descriptors_alloc.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/border_descriptors_alloc.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Memory_Alloc/buddy_alloc.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/buddy_alloc.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/buddy_alloc.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Memory_Alloc/global_heap_alloc.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/global_heap_alloc.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/global_heap_alloc.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Memory_Alloc/hold_memory.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/hold_memory.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/hold_memory.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Memory_Alloc/memory.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/memory.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/memory.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Memory_Alloc/sorted_list_alloc.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/sorted_list_alloc.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Memory_Alloc/sorted_list_alloc.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_add_collection.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_collection.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_collection.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_add_data.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_data.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_data.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_add_pool.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_pool.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_pool.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_add_scheme.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_scheme.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_add_scheme.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_get_data.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_get_data_between.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data_between.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_get_data_between.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_remove_collection.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_collection.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_collection.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_remove_data.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_data.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_data.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_remove_pool.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_pool.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_pool.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_remove_scheme.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_scheme.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_remove_scheme.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/command_update_data.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_update_data.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/command_update_data.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/request_handler_with_command.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/Request_Handler/request_handler_with_command_chain.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command_chain.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/Request_Handler/request_handler_with_command_chain.cpp.obj.d"
  "E:/Downloads/OLDKURSACHI/fundamental-algorithms-main/fundamental-algorithms-main/4Term/Zaitsevs_cursed_project/main.cpp" "CMakeFiles/Zaitsevs_cursed_project.dir/main.cpp.obj" "gcc" "CMakeFiles/Zaitsevs_cursed_project.dir/main.cpp.obj.d"
  )

# Targets to which this target links.
set(CMAKE_TARGET_LINKED_INFO_FILES
  )

# Fortran module output directory.
set(CMAKE_Fortran_TARGET_MODULE_DIR "")
